//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webinar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCardInfo
    {
        public int cardid { get; set; }
        public Nullable<int> customerid { get; set; }
        public string cardno { get; set; }
        public string cardtype { get; set; }
        public string expyear { get; set; }
        public string expmonth { get; set; }
        public string expday { get; set; }
        public Nullable<System.DateTime> expdate { get; set; }
        public Nullable<System.DateTime> lastused { get; set; }
        public Nullable<decimal> amtused { get; set; }
        public Nullable<decimal> amtusedytd { get; set; }
    }
}
