//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webinar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int PI_id { get; set; }
        public string PI_fname { get; set; }
        public string PI_lname { get; set; }
        public string PI_email { get; set; }
        public string PI_password { get; set; }
        public string PI_phone_number { get; set; }
        public Nullable<System.DateTime> PI_created_date { get; set; }
        public Nullable<System.DateTime> PI_last_access_dt { get; set; }
        public string PI_zoom_user_id { get; set; }
        public Nullable<bool> PI_IsLoggedIn { get; set; }
        public string PI_timezone { get; set; }
        public Nullable<bool> PI_Isadmin { get; set; }
    }
}
