//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webinar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWebinarDetail
    {
        public int WebinarId { get; set; }
        public Nullable<int> WebinaruserId { get; set; }
        public string Webinar_starturl { get; set; }
        public string Webinar_joinurl { get; set; }
        public Nullable<System.DateTime> Webinar_starttime { get; set; }
        public Nullable<System.DateTime> Webinar_endtime { get; set; }
        public Nullable<int> Webinar_duration { get; set; }
        public Nullable<int> Webinar_type { get; set; }
        public string Webinar_timezone { get; set; }
        public string Webinar_meeting_id { get; set; }
        public Nullable<int> Webinar_meeting_status { get; set; }
        public string Webinar_host_id { get; set; }
    }
}
