//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTestDataAssess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public long AnswerId { get; set; }
        public Nullable<long> QuestionId { get; set; }
        public string Answer1 { get; set; }
        public bool IsActive { get; set; }
    }
}
