//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTestDataAssess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public long QuestionId { get; set; }
        public string Question1 { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> CorrectAnswerId { get; set; }
        public string CorrectAnswer { get; set; }
    }
}
