//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTestDataAssess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public long TestId { get; set; }
        public string UserId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> TotalQuestion { get; set; }
        public Nullable<int> Attempted { get; set; }
        public Nullable<int> Correct { get; set; }
    }
}
